version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-taskdb
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-task-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=taskuser
      - DB_PASSWORD=taskpassword
      - DB_NAME=taskdb
    depends_on:
      - postgres
    restart: always

volumes:
  postgres-data: